version: "3.3"

services:
  web:
    build: ./web      # 从该目录下的 Dockerfile 构建容器
    container_name: a_c_app_web
    ports:
      - "5000:80"
    depends_on:
      - mysql
    volumes:
      - ./web:/code
    networks:
      - app_net
  mysql:
    image: mysql:5.7
    container_name: a_c_app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret_passwd
    ports:
      - "5001:3306"
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d    # 开机运行脚本：初始化脚本
      - ./mysql/data:/var/lib/mysql     # mysql 数据
      - ./mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf    # 配置
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
